version: "3.9"
services:
  transform_job:
    build: .
    environment:
      - SPARK_LOCAL_DIR=./spark-data
      - CASSANDRA_HOST=cassandra_eth_transform
      - SPARK_EXECUTOR_MEMORY=8g
      - RAW_KEYSPACE=eth_raw
      - TGT_KEYSPACE=eth_transformed
    # volumes:
    #   - "./src:/opt/graphsense/src"
    command: bash -c "timeout 3m bash -c 'until cqlsh cassandra_eth_transform; do sleep 10; done' && ./init_test_db.sh && ./scripts/dsbulk_load.sh && ./submit.sh "
    #command: ./submit.sh
    networks:
      - backend

  cassandra_eth_transform:
    image: "cassandra:4.0"
    volumes:
      - cassandra-test-data:/var/lib/cassandra 
    ports:
      - "9042:9042"
    networks:
      - backend

networks:
  backend:

volumes:
  cassandra-test-data:
